name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: '0 */2 * * *'


jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS: "False"
          SHOW_PROJECTS: "True"
          SHOW_LINES_OF_CODE: "True"
          LOCALE: "en"
          SHOW_TITLE: true # optional
          SECTION_NAME: waka # optional
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿ # optional
          CODE_LANG: javascript # optional
          TIME_RANGE: last_year # optional
          LANG_COUNT: 10 # optional
          SHOW_TIME: true # optional
          SHOW_TOTAL: true # optional
          SHOW_MASKED_TIME: false # optional
          STOP_AT_OTHER: true # optional
          IGNORED_LANGUAGES: Markdown
